version: "3"
services:
    # Web
    web:
        image: nginx
        volumes:
          - ".:/app"
          - "./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf"
          - "./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini"
        container_name: webserver
        depends_on:
          - php
        ports:
          - "8000:80"
    php:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: patterns
        volumes:
            - ".:/app"
            - "./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini"