decorator:
  path: /patterns/decorator
  controller: App\Controller\ExamplesController::decorator
  methods: [GET]

builderWithChaining:
  path: /patterns/builder/chaining
  controller: App\Controller\ExamplesController::builderWithChaining
  methods: [GET]